### ISSUE TITLE
[Project] 개발 환경 구축

### ISSUE THREAD

**Issue by Sehee-Park-93** [codestates/Cogether#11]
### **ISSUE**

- Group: `client`, `server`
- Type: 구축
- Detail: 개발 환경 구축

### **TODO**

- [ ]  Upstream dev 브랜치 생성
- [ ]  Upstream dev 클론 to 로컬
- [ ]  개발 환경 구축
