### ISSUE TITLE
[Server] 회원 정보 수정 로직 변경

### ISSUE THREAD

**Issue by Sehee-Park-93** [codestates/Cogether#114]
### **ISSUE**

- Group: `server`
- Type: `feature`
- Detail: fix actions from client redux

### **TODO**

- [ ]  닉네임 중복 검사 및 수정코드 변경
- [ ]  프로필 이미지 첨부, 삭제 관련 코드 변경
- [ ]  배포 환경 최종 테스트
