### ISSUE TITLE
[Server] 게시판 전체 조회 기능

### ISSUE THREAD

**Issue by Sehee-Park-93** [codestates/Cogether#138]
### **ISSUE**

- Group: `client`
- Type: `feature`
- Detail: 메인페이지 접속시 전체 게시물을 업로드 하기 위한 API 컨트롤러 구성

### **TODO**

- [ ]  controllers/getAllPosts.js 컨트롤러 구축
- [ ]  전체 게시물 데이터베이스에서 조회 후 최신, 인기 순으로 정렬하여 응답에 담아보내주기
- [ ]  로컬에서 테스트 후 이상 없을 시 PR 요청하기
