### ISSUE TITLE
[Server] 게시판 작성 기능(추가)

### ISSUE THREAD

**Issue by Sehee-Park-93** [codestates/Cogether#139]
### **ISSUE**

- Group: `server`
- Type: `feature`
- Detail: 게시판 작성 기능 추가

### **TODO**

- [ ]  controllers/createPost.js 컨트롤러 구축
- [ ]  작성 후 API 문서 참고 후 응답에 클라이언트가 올바른 바디 데이터 담아 보내기
- [ ]  로컬에서 테스트 후 이상없을 시 PR 요청
