### ISSUE TITLE
[Server] 내가 쓴 게시글 조회하는 기능

### ISSUE THREAD

**Issue by Sehee-Park-93** [codestates/Cogether#141]
### **ISSUE**

- Group: `server`
- Type: `feature`
- Detail: 게시글 목록 중 내가 쓴 글만 볼 수 있게 하는 기능 API 작성

### **TODO**

- [ ]  controllers/getMyPosts.js 컨트롤러 구축
- [ ]  클라이언트에 필요한 데이터 응답 바디에 담아서 보내기
- [ ]  로컬 API 통신 테스트 후 PR 요청
