### ISSUE TITLE
[Server] 게시판 상세 조회 기능

### ISSUE THREAD

**Issue by Sehee-Park-93** [codestates/Cogether#144]
### **ISSUE**

- Group: `server`
- Type:  `feature`
- Detail: 게시판의 고유 id를 엔드포인트로 받아 게시물을 상세 조회 기능

### **TODO**

- [ ]  posts/getPostDetail.js 컨트롤러 구축
- [ ]  게시물 조회 및 조회수 증가 로직 구현
- [ ]  포스트맨으로 로컬 통신 후 커밋 , PR 요청
