### ISSUE TITLE
[Server] 게시글 삭제 기능

### ISSUE THREAD

**Issue by Sehee-Park-93** [codestates/Cogether#148]
### **ISSUE**

- Group: `server`
- Type:  `feature`
- Detail: 게시판 작성 된 게시글 삭제하는 기능

### **TODO**

- [ ]  posts/deletePosts.js 컨트롤러 구축
- [ ]  req.params로 받아온 id로 데이터 처리
- [ ]  로컬 데이터베이스에서 테스트 후 PR 요청하기
