### ISSUE TITLE
[Server] 게시판 기능 브라우저 환경 테스트 후 피드백 반영

### ISSUE THREAD

**Issue by Sehee-Park-93** [codestates/Cogether#157]
### **ISSUE**

- Group: `server`
- Type: `bug`, `update`
- Detail: 구현 완료한 기능을 로컬 브라우저 환경에서 전체 병합된 코드로 테스트 후 피드백 수정 반영

### **TODO**

- [ ]  PR 후 전체 코드 머지
- [ ]  로컬 브라우저 환경에서의 UI&UX 테스트 시 데이터 처리 체크
- [ ]  피드백 발생시 수정 반영
