### ISSUE TITLE
[Server] 게시판 수정 기능

### ISSUE THREAD

**Issue by Sehee-Park-93** [codestates/Cogether#158]
### **ISSUE**

- Group: `server`
- Type: `feature`
- Detail: 작성한 게시판을 필요시 수정할 수 있는 기능 구현

### **TODO**

- [ ]  posts/updatePost.js 컨트롤러 구축
- [ ]  코드 작성시 수정하는 과정 및 데이터 처리 꼼꼼히 체크
- [ ]  로컬환경에서의 테스트 후 이상없을 시 PR
