### ISSUE TITLE
[Server] https 배포 환경 점검 및 에러 핸들링

### ISSUE THREAD

**Issue by Sehee-Park-93** [codestates/Cogether#170]
### **ISSUE**

- Group: `server`
- Type: `error handling`
- Detail: AWS EC2,RDS,ELB 배포환경에서의 작동 체크 및 에러 핸들링

### **TODO**

- [ ]  코드 파이프라인 가동
- [ ]  배포환경에서의 서버 가동
- [ ]  클라이언트와의 통신 및 UI 점검
