### ISSUE TITLE
[Project] 레포지토리 WIKI 문서 작성

### ISSUE THREAD

**Issue by Sehee-Park-93** [codestates/Cogether#227]
### **ISSUE**

- Group: `sr`
- Type:  `documentation`
- Detail: 프로젝트 마무리 단계 문서화 작업

### **TODO**

- [ ]  WIKI 작성 및 점검
- [ ]  브랜치 Upstrem master로 최종 병합
- [ ]  Readme.md 파일 꾸미기
