### ISSUE TITLE
[Server] 유저 회원가입 컨트롤러

### ISSUE THREAD

**Issue by Sehee-Park-93** [codestates/Cogether#32]
### **ISSUE**

- Group: `server`
- Type: `feature`
- Detail: 유저 회원가입 컨트롤러 구현

### **TODO**

- [ ]  signup.js 컨트롤러 구현
- [ ]  API 문서 참고, 반영 하여 코드 구현
- [ ]  구현 후 Postman으로 요청 응답 테스트
