### ISSUE TITLE
[Server] utils/helpFunc 구축

### ISSUE THREAD

**Issue by Sehee-Park-93** [codestates/Cogether#33]
### **ISSUE**

- Group: `server`
- Type: `feature`
- Detail: 서버의 유저 인증과 비밀번호 해싱해주는 유틸 함수 구축

### **TODO**

- [ ]  utils/helpFunc.js 폴더, 파일 생성
- [ ]  bcyript 공식문서 , 유어클래스 참조하여 코드 구성
- [ ]  추후 API 통신으로 테스트
